name: calling reusable workflow
on:
  workflow_dispatch: 
    inputs:
      name:
        description: Provide the name of the person
        required: true
        type: string

jobs:
    call-reuable-workflow:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            name: ${{ inputs.name }}