name: reusable-workflow
on:
  workflow_call:
    inputs:
      name: 
        required: true
        description: name of the person
        type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Run a one-line script
              run: echo "Hello, ${{ inputs.name }}!"